// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCiliumFlowTaggers implements CiliumFlowTaggerInterface
type fakeCiliumFlowTaggers struct {
	*gentype.FakeClientWithList[*v2alpha1.CiliumFlowTagger, *v2alpha1.CiliumFlowTaggerList]
	Fake *FakeCiliumV2alpha1
}

func newFakeCiliumFlowTaggers(fake *FakeCiliumV2alpha1) ciliumiov2alpha1.CiliumFlowTaggerInterface {
	return &fakeCiliumFlowTaggers{
		gentype.NewFakeClientWithList[*v2alpha1.CiliumFlowTagger, *v2alpha1.CiliumFlowTaggerList](
			fake.Fake,
			"",
			v2alpha1.SchemeGroupVersion.WithResource("ciliumflowtaggers"),
			v2alpha1.SchemeGroupVersion.WithKind("CiliumFlowTagger"),
			func() *v2alpha1.CiliumFlowTagger { return &v2alpha1.CiliumFlowTagger{} },
			func() *v2alpha1.CiliumFlowTaggerList { return &v2alpha1.CiliumFlowTaggerList{} },
			func(dst, src *v2alpha1.CiliumFlowTaggerList) { dst.ListMeta = src.ListMeta },
			func(list *v2alpha1.CiliumFlowTaggerList) []*v2alpha1.CiliumFlowTagger {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v2alpha1.CiliumFlowTaggerList, items []*v2alpha1.CiliumFlowTagger) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
