// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by informer-gen. DO NOT EDIT.

package v2alpha1

import (
	context "context"
	time "time"

	apisciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	versioned "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/cilium/cilium/pkg/k8s/client/informers/externalversions/internalinterfaces"
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/client/listers/cilium.io/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CiliumFlowTaggerInformer provides access to a shared informer and lister for
// CiliumFlowTaggers.
type CiliumFlowTaggerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() ciliumiov2alpha1.CiliumFlowTaggerLister
}

type ciliumFlowTaggerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCiliumFlowTaggerInformer constructs a new informer for CiliumFlowTagger type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCiliumFlowTaggerInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCiliumFlowTaggerInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredCiliumFlowTaggerInformer constructs a new informer for CiliumFlowTagger type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCiliumFlowTaggerInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CiliumV2alpha1().CiliumFlowTaggers().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CiliumV2alpha1().CiliumFlowTaggers().Watch(context.TODO(), options)
			},
		},
		&apisciliumiov2alpha1.CiliumFlowTagger{},
		resyncPeriod,
		indexers,
	)
}

func (f *ciliumFlowTaggerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCiliumFlowTaggerInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ciliumFlowTaggerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisciliumiov2alpha1.CiliumFlowTagger{}, f.defaultInformer)
}

func (f *ciliumFlowTaggerInformer) Lister() ciliumiov2alpha1.CiliumFlowTaggerLister {
	return ciliumiov2alpha1.NewCiliumFlowTaggerLister(f.Informer().GetIndexer())
}
