// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CiliumFlowTaggerLister helps list CiliumFlowTaggers.
// All objects returned here must be treated as read-only.
type CiliumFlowTaggerLister interface {
	// List lists all CiliumFlowTaggers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ciliumiov2alpha1.CiliumFlowTagger, err error)
	// Get retrieves the CiliumFlowTagger from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ciliumiov2alpha1.CiliumFlowTagger, error)
	CiliumFlowTaggerListerExpansion
}

// ciliumFlowTaggerLister implements the CiliumFlowTaggerLister interface.
type ciliumFlowTaggerLister struct {
	listers.ResourceIndexer[*ciliumiov2alpha1.CiliumFlowTagger]
}

// NewCiliumFlowTaggerLister returns a new CiliumFlowTaggerLister.
func NewCiliumFlowTaggerLister(indexer cache.Indexer) CiliumFlowTaggerLister {
	return &ciliumFlowTaggerLister{listers.New[*ciliumiov2alpha1.CiliumFlowTagger](indexer, ciliumiov2alpha1.Resource("ciliumflowtagger"))}
}
